logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%highlight(%-5p)) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
spring:
  rabbitmq:
    addresses: "localhost:5672"
    username: guest
    password: guest
  main:
    banner-mode: OFF